"""Manual XRP boot-file recovery helpers.

This module intentionally has no display, camera, SD, or EmotionLib imports and
does not run any repair action when imported. Call its functions explicitly
from a MicroPython REPL.
"""

import os
import sys


SAFE_MAIN_MARKER = "Safe development boot file generated by XRPWeb Boot Safety."

SAFE_MAIN_CONTENT = '''# main.py
# Safe development boot file generated by XRPWeb Boot Safety.
# It prevents automatic execution of user programs during file upload/debugging.

import os
import sys
import gc

FILE_PATH = "/lib/ble/isrunning"

try:
    x = os.dupterm(None, 0)
    if x is None:
        try:
            import ble.blerepl
        except Exception:
            pass
    else:
        os.dupterm(x, 0)
except Exception:
    pass

try:
    try:
        with open(FILE_PATH, "r+b") as file:
            byte = file.read(1)
            if byte == b"\\x01":
                file.seek(0)
                file.write(b"\\x00")
    except Exception:
        pass
finally:
    gc.collect()
    try:
        if "XRPLib.resetbot" in sys.modules:
            del sys.modules["XRPLib.resetbot"]
        import XRPLib.resetbot
    except Exception:
        pass
'''


def _exists(path):
    try:
        os.stat(path)
        return True
    except OSError:
        return False


def _read(path, limit=None):
    handle = open(path, "r")
    try:
        return handle.read() if limit is None else handle.read(limit)
    finally:
        handle.close()


def _write(path, content):
    handle = open(path, "w")
    try:
        handle.write(content)
    finally:
        handle.close()


def _backups():
    indexed = []
    for name in os.listdir("/"):
        if name == "main_autorun_backup.py":
            indexed.append((0, "/" + name))
        elif name.startswith("main_autorun_backup_") and name.endswith(".py"):
            number = name[20:-3]
            if number.isdigit():
                indexed.append((int(number), "/" + name))
    indexed.sort()
    return [item[1] for item in indexed]


def _next_backup():
    path = "/main_autorun_backup.py"
    if not _exists(path):
        return path
    index = 1
    while True:
        path = "/main_autorun_backup_" + str(index) + ".py"
        if not _exists(path):
            return path
        index += 1


def _clean_message(error):
    return str(error).replace("\r", " ").replace("\n", " ")[:240]


def inspect_boot():
    """Inspect /main.py and print the Boot Safety sentinel protocol."""
    try:
        main_exists = _exists("/main.py")
        prueba_exists = _exists("/prueba.py")
        content = _read("/main.py", 2000) if main_exists else ""
        compact = "".join(content.lower().split())
        is_safe = SAFE_MAIN_MARKER in content
        has_exec = "exec(" in compact
        has_compile = "compile(" in compact
        prueba_open = (
            "open('/prueba.py'" in compact
            or 'open("/prueba.py"' in compact
        )
        prueba_autorun = prueba_open and (has_exec or has_compile)
        autorun = (not is_safe) and (prueba_autorun or has_exec or has_compile)
        print("BOOT_SAFETY:STATUS=OK")
        print("BOOT_SAFETY:ACTION=INSPECT")
        print("BOOT_SAFETY:MAIN_EXISTS=" + ("1" if main_exists else "0"))
        print("BOOT_SAFETY:MAIN_IS_SAFE=" + ("1" if is_safe else "0"))
        print("BOOT_SAFETY:AUTORUN_DETECTED=" + ("1" if autorun else "0"))
        print("BOOT_SAFETY:PRUEBA_EXISTS=" + ("1" if prueba_exists else "0"))
        print(
            "BOOT_SAFETY:PRUEBA_AUTORUN_DETECTED="
            + ("1" if prueba_autorun else "0")
        )
        print("BOOT_SAFETY:PROGRAM_TARGET=" + ("/prueba.py" if prueba_autorun else ""))
        print("BOOT_SAFETY:BACKUPS=" + ",".join(_backups()))
        print("BOOT_SAFETY:MAIN_PREVIEW_BEGIN")
        print(content)
        print("BOOT_SAFETY:MAIN_PREVIEW_END")
        print("BOOT_SAFETY:MESSAGE=Boot files inspected")
        return {
            "main_exists": main_exists,
            "main_is_safe": is_safe,
            "autorun_detected": autorun,
            "prueba_autorun_detected": prueba_autorun,
            "backups": _backups(),
        }
    except Exception as error:
        sys.print_exception(error)
        print("BOOT_SAFETY:STATUS=ERROR")
        print("BOOT_SAFETY:ACTION=INSPECT")
        print("BOOT_SAFETY:MESSAGE=" + _clean_message(error))
        return None


def write_safe_main():
    """Write and verify the generated safe /main.py without making a backup."""
    _write("/main.py", SAFE_MAIN_CONTENT)
    if _read("/main.py") != SAFE_MAIN_CONTENT:
        raise Exception("Safe main verification failed")
    return True


def disable_autorun():
    """Back up a non-safe /main.py, then install the safe development boot."""
    backup_path = ""
    try:
        main_exists = _exists("/main.py")
        current = _read("/main.py") if main_exists else ""
        if SAFE_MAIN_MARKER in current:
            message = "Autorun is already disabled"
            safe_written = False
        else:
            if main_exists:
                backup_path = _next_backup()
                os.rename("/main.py", backup_path)
            try:
                write_safe_main()
            except Exception:
                if _exists("/main.py"):
                    os.remove("/main.py")
                if backup_path and _exists(backup_path):
                    os.rename(backup_path, "/main.py")
                raise
            message = "Autorun disabled safely"
            safe_written = True
        print("BOOT_SAFETY:STATUS=OK")
        print("BOOT_SAFETY:ACTION=DISABLE_AUTORUN")
        print("BOOT_SAFETY:BACKUP_PATH=" + backup_path)
        print("BOOT_SAFETY:SAFE_MAIN_WRITTEN=" + ("1" if safe_written else "0"))
        print("BOOT_SAFETY:MESSAGE=" + message)
        return backup_path
    except Exception as error:
        sys.print_exception(error)
        print("BOOT_SAFETY:STATUS=ERROR")
        print("BOOT_SAFETY:ACTION=DISABLE_AUTORUN")
        print("BOOT_SAFETY:BACKUP_PATH=" + backup_path)
        print("BOOT_SAFETY:MESSAGE=" + _clean_message(error))
        return None


def restore_autorun(backup_path="/main_autorun_backup.py"):
    """Copy a selected backup to /main.py while preserving every backup."""
    temporary_path = "/main_boot_safety_restore_tmp.py"
    current_backup_path = ""
    current_exists = False
    current_content = ""
    try:
        if not _exists(backup_path):
            raise Exception("No autorun backup found")
        restore_content = _read(backup_path)
        if _exists(temporary_path):
            os.remove(temporary_path)
        _write(temporary_path, restore_content)
        if _read(temporary_path) != restore_content:
            raise Exception("Restore file verification failed")
        current_exists = _exists("/main.py")
        current_content = _read("/main.py") if current_exists else ""
        if current_exists and current_content != SAFE_MAIN_CONTENT:
            current_backup_path = _next_backup()
            _write(current_backup_path, current_content)
            if _read(current_backup_path) != current_content:
                raise Exception("Current main backup verification failed")
        if current_exists:
            os.remove("/main.py")
        os.rename(temporary_path, "/main.py")
        if _read("/main.py") != restore_content:
            raise Exception("Restored main verification failed")
        print("BOOT_SAFETY:STATUS=OK")
        print("BOOT_SAFETY:ACTION=RESTORE_AUTORUN")
        print("BOOT_SAFETY:BACKUP_PATH=" + backup_path)
        print("BOOT_SAFETY:CURRENT_BACKUP_PATH=" + current_backup_path)
        print("BOOT_SAFETY:MESSAGE=Autorun restored")
        return True
    except Exception as error:
        if not _exists("/main.py") and current_exists:
            try:
                _write("/main.py", current_content)
            except Exception as rollback_error:
                sys.print_exception(rollback_error)
        if _exists(temporary_path):
            try:
                os.remove(temporary_path)
            except Exception:
                pass
        sys.print_exception(error)
        print("BOOT_SAFETY:STATUS=ERROR")
        print("BOOT_SAFETY:ACTION=RESTORE_AUTORUN")
        print("BOOT_SAFETY:BACKUPS=" + ",".join(_backups()))
        print("BOOT_SAFETY:MESSAGE=" + _clean_message(error))
        return False
