export const BOOT_SAFETY_MARKER =
  "Safe development boot file generated by XRPWeb Boot Safety.";

export const SAFE_MAIN_CONTENT = `# main.py
# Safe development boot file generated by XRPWeb Boot Safety.
# It prevents automatic execution of user programs during file upload/debugging.

import os
import sys
import gc

FILE_PATH = "/lib/ble/isrunning"

try:
    x = os.dupterm(None, 0)
    if x is None:
        try:
            import ble.blerepl
        except Exception:
            pass
    else:
        os.dupterm(x, 0)
except Exception:
    pass

try:
    try:
        with open(FILE_PATH, "r+b") as file:
            byte = file.read(1)
            if byte == b"\\x01":
                file.seek(0)
                file.write(b"\\x00")
    except Exception:
        pass
finally:
    gc.collect()
    try:
        if "XRPLib.resetbot" in sys.modules:
            del sys.modules["XRPLib.resetbot"]
        import XRPLib.resetbot
    except Exception:
        pass
`;

export type MainBootAnalysis = {
  isSafe: boolean;
  autorunDetected: boolean;
  pruebaAutorunDetected: boolean;
  programTarget?: string;
};

export type BootSafetyReport = {
  status: "OK" | "ERROR" | "UNKNOWN";
  action?: string;
  message: string;
  mainExists?: boolean;
  mainIsSafe?: boolean;
  autorunDetected?: boolean;
  pruebaExists?: boolean;
  pruebaAutorunDetected?: boolean;
  programTarget?: string;
  safeMainWritten?: boolean;
  backupPath?: string;
  currentBackupPath?: string;
  backups: string[];
  mainPreview: string;
  fields: Record<string, string>;
};

const BACKUP_BASE = "/main_autorun_backup.py";
const BACKUP_PREFIX = "/main_autorun_backup_";

export function selectBackupPath(existingPaths: readonly string[]): string {
  const existing = new Set(existingPaths);

  if (!existing.has(BACKUP_BASE)) {
    return BACKUP_BASE;
  }

  let index = 1;
  while (existing.has(`${BACKUP_PREFIX}${index}.py`)) {
    index += 1;
  }

  return `${BACKUP_PREFIX}${index}.py`;
}

export function analyzeMainContent(content: string): MainBootAnalysis {
  const compact = content.toLowerCase().replace(/\s+/g, "");
  const targetMatch = content.match(
    /(?:with\s+)?open\s*\(\s*["'](\/[^"']+\.py)["']/i,
  );
  const hasExec = /\bexec\s*\(/i.test(content);
  const hasCompile = /\bcompile\s*\(/i.test(content);
  const pruebaOpen =
    compact.includes("open('/prueba.py'") ||
    compact.includes('open("/prueba.py"');
  const pruebaAutorunDetected = pruebaOpen && (hasExec || hasCompile);

  return {
    isSafe: content.includes(BOOT_SAFETY_MARKER),
    autorunDetected:
      !content.includes(BOOT_SAFETY_MARKER) &&
      (pruebaAutorunDetected ||
        ((hasExec || hasCompile) && targetMatch !== null)),
    pruebaAutorunDetected,
    programTarget: pruebaAutorunDetected
      ? "/prueba.py"
      : targetMatch?.[1],
  };
}

function parseBoolean(value: string | undefined): boolean | undefined {
  if (value === "1") return true;
  if (value === "0") return false;
  return undefined;
}

export function parseBootSafetyOutput(output: string): BootSafetyReport {
  const normalized = output.replace(/\r/g, "");
  const fields: Record<string, string> = {};
  const fieldPattern = /BOOT_SAFETY:([A-Z_]+)=([^\n]*)/g;

  for (const match of normalized.matchAll(fieldPattern)) {
    fields[match[1]] = match[2].trim();
  }

  const previewStart = "BOOT_SAFETY:MAIN_PREVIEW_BEGIN";
  const previewEnd = "BOOT_SAFETY:MAIN_PREVIEW_END";
  const startIndex = normalized.indexOf(previewStart);
  const endIndex =
    startIndex >= 0
      ? normalized.indexOf(previewEnd, startIndex + previewStart.length)
      : -1;
  let mainPreview = "";

  if (startIndex >= 0 && endIndex >= 0) {
    mainPreview = normalized
      .slice(startIndex + previewStart.length, endIndex)
      .replace(/^\n/, "")
      .replace(/\n$/, "")
      .slice(0, 2000);
  }

  const previewAnalysis = analyzeMainContent(mainPreview);
  const backups = (fields.BACKUPS ?? "")
    .split(",")
    .map((path) => path.trim())
    .filter(Boolean);

  if (fields.BACKUP_PATH && !backups.includes(fields.BACKUP_PATH)) {
    backups.push(fields.BACKUP_PATH);
  }

  return {
    status:
      fields.STATUS === "OK" || fields.STATUS === "ERROR"
        ? fields.STATUS
        : "UNKNOWN",
    action: fields.ACTION,
    message: fields.MESSAGE ?? "No Boot Safety response received.",
    mainExists: parseBoolean(fields.MAIN_EXISTS),
    mainIsSafe:
      parseBoolean(fields.MAIN_IS_SAFE) ??
      (mainPreview ? previewAnalysis.isSafe : undefined),
    autorunDetected:
      parseBoolean(fields.AUTORUN_DETECTED) ??
      (mainPreview ? previewAnalysis.autorunDetected : undefined),
    pruebaExists: parseBoolean(fields.PRUEBA_EXISTS),
    pruebaAutorunDetected:
      parseBoolean(fields.PRUEBA_AUTORUN_DETECTED) ??
      (mainPreview ? previewAnalysis.pruebaAutorunDetected : undefined),
    programTarget:
      fields.PROGRAM_TARGET || previewAnalysis.programTarget,
    safeMainWritten: parseBoolean(fields.SAFE_MAIN_WRITTEN),
    backupPath: fields.BACKUP_PATH || undefined,
    currentBackupPath: fields.CURRENT_BACKUP_PATH || undefined,
    backups,
    mainPreview,
    fields,
  };
}

const SAFE_MAIN_PYTHON_LITERAL = `r'''${SAFE_MAIN_CONTENT}'''`;

const COMMON_SCRIPT_HELPERS = `
def boot_safety_exists(path):
    try:
        os.stat(path)
        return True
    except OSError:
        return False

def boot_safety_read(path, limit=None):
    handle = open(path, "r")
    try:
        return handle.read() if limit is None else handle.read(limit)
    finally:
        handle.close()

def boot_safety_write(path, content):
    handle = open(path, "w")
    try:
        handle.write(content)
    finally:
        handle.close()

def boot_safety_backups():
    indexed = []
    for name in os.listdir("/"):
        if name == "main_autorun_backup.py":
            indexed.append((0, "/" + name))
        elif name.startswith("main_autorun_backup_") and name.endswith(".py"):
            number = name[20:-3]
            if number.isdigit():
                indexed.append((int(number), "/" + name))
    indexed.sort()
    return [item[1] for item in indexed]

def boot_safety_next_backup():
    path = "/main_autorun_backup.py"
    if not boot_safety_exists(path):
        return path
    index = 1
    while True:
        path = "/main_autorun_backup_" + str(index) + ".py"
        if not boot_safety_exists(path):
            return path
        index += 1

def boot_safety_message(error):
    return str(error).replace("\\r", " ").replace("\\n", " ")[:240]
`;

export function buildInspectScript(): string {
  return `import os
import sys
${COMMON_SCRIPT_HELPERS}
try:
    main_exists = boot_safety_exists("/main.py")
    prueba_exists = boot_safety_exists("/prueba.py")
    content = boot_safety_read("/main.py", 2000) if main_exists else ""
    compact = "".join(content.lower().split())
    main_is_safe = ${JSON.stringify(BOOT_SAFETY_MARKER)} in content
    has_exec = "exec(" in compact
    has_compile = "compile(" in compact
    prueba_open = ("open('/prueba.py'" in compact or 'open("/prueba.py"' in compact)
    prueba_autorun = prueba_open and (has_exec or has_compile)
    autorun = (not main_is_safe) and (prueba_autorun or has_exec or has_compile)
    backups = boot_safety_backups()
    print("BOOT_SAFETY:STATUS=OK")
    print("BOOT_SAFETY:ACTION=INSPECT")
    print("BOOT_SAFETY:MAIN_EXISTS=" + ("1" if main_exists else "0"))
    print("BOOT_SAFETY:MAIN_IS_SAFE=" + ("1" if main_is_safe else "0"))
    print("BOOT_SAFETY:AUTORUN_DETECTED=" + ("1" if autorun else "0"))
    print("BOOT_SAFETY:PRUEBA_EXISTS=" + ("1" if prueba_exists else "0"))
    print("BOOT_SAFETY:PRUEBA_AUTORUN_DETECTED=" + ("1" if prueba_autorun else "0"))
    print("BOOT_SAFETY:PROGRAM_TARGET=" + ("/prueba.py" if prueba_autorun else ""))
    print("BOOT_SAFETY:BACKUPS=" + ",".join(backups))
    print("BOOT_SAFETY:MAIN_PREVIEW_BEGIN")
    print(content)
    print("BOOT_SAFETY:MAIN_PREVIEW_END")
    print("BOOT_SAFETY:MESSAGE=Boot files inspected")
except Exception as error:
    sys.print_exception(error)
    print("BOOT_SAFETY:STATUS=ERROR")
    print("BOOT_SAFETY:ACTION=INSPECT")
    print("BOOT_SAFETY:MESSAGE=" + boot_safety_message(error))
print("BOOT_SAFETY:SCRIPT_DONE")
`;
}

export function buildDisableAutorunScript(): string {
  return `import os
import sys
${COMMON_SCRIPT_HELPERS}
safe_main = ${SAFE_MAIN_PYTHON_LITERAL}
backup_path = ""
main_existed = False
try:
    main_existed = boot_safety_exists("/main.py")
    current = boot_safety_read("/main.py") if main_existed else ""
    if ${JSON.stringify(BOOT_SAFETY_MARKER)} in current:
        safe_written = False
        message = "Autorun is already disabled"
    else:
        if main_existed:
            backup_path = boot_safety_next_backup()
            os.rename("/main.py", backup_path)
        try:
            boot_safety_write("/main.py", safe_main)
            if boot_safety_read("/main.py") != safe_main:
                raise Exception("Safe main verification failed")
        except Exception:
            if boot_safety_exists("/main.py"):
                os.remove("/main.py")
            if backup_path and boot_safety_exists(backup_path):
                os.rename(backup_path, "/main.py")
            raise
        safe_written = True
        message = "Autorun disabled safely"
    print("BOOT_SAFETY:STATUS=OK")
    print("BOOT_SAFETY:ACTION=DISABLE_AUTORUN")
    print("BOOT_SAFETY:MAIN_EXISTS=" + ("1" if main_existed else "0"))
    print("BOOT_SAFETY:MAIN_IS_SAFE=1")
    print("BOOT_SAFETY:AUTORUN_DETECTED=0")
    print("BOOT_SAFETY:BACKUP_PATH=" + backup_path)
    print("BOOT_SAFETY:BACKUPS=" + ",".join(boot_safety_backups()))
    print("BOOT_SAFETY:SAFE_MAIN_WRITTEN=" + ("1" if safe_written else "0"))
    print("BOOT_SAFETY:MESSAGE=" + message)
except Exception as error:
    sys.print_exception(error)
    print("BOOT_SAFETY:STATUS=ERROR")
    print("BOOT_SAFETY:ACTION=DISABLE_AUTORUN")
    print("BOOT_SAFETY:BACKUP_PATH=" + backup_path)
    print("BOOT_SAFETY:MESSAGE=" + boot_safety_message(error))
print("BOOT_SAFETY:SCRIPT_DONE")
`;
}

function pythonStringLiteral(value: string): string {
  return JSON.stringify(value);
}

export function buildRestoreAutorunScript(backupPath: string): string {
  return `import os
import sys
${COMMON_SCRIPT_HELPERS}
safe_main = ${SAFE_MAIN_PYTHON_LITERAL}
selected_backup = ${pythonStringLiteral(backupPath)}
temporary_path = "/main_boot_safety_restore_tmp.py"
current_backup_path = ""
current_existed = False
current_content = ""
try:
    valid_backup = (selected_backup == "/main_autorun_backup.py" or (selected_backup.startswith("/main_autorun_backup_") and selected_backup.endswith(".py") and selected_backup[21:-3].isdigit()))
    if not valid_backup:
        raise Exception("Invalid autorun backup path")
    if not boot_safety_exists(selected_backup):
        raise Exception("No autorun backup found")
    restore_content = boot_safety_read(selected_backup)
    if boot_safety_exists(temporary_path):
        os.remove(temporary_path)
    boot_safety_write(temporary_path, restore_content)
    if boot_safety_read(temporary_path) != restore_content:
        raise Exception("Restore file verification failed")
    current_existed = boot_safety_exists("/main.py")
    current_content = boot_safety_read("/main.py") if current_existed else ""
    if current_existed and current_content != safe_main:
        current_backup_path = boot_safety_next_backup()
        boot_safety_write(current_backup_path, current_content)
        if boot_safety_read(current_backup_path) != current_content:
            raise Exception("Current main backup verification failed")
    if current_existed:
        os.remove("/main.py")
    os.rename(temporary_path, "/main.py")
    if boot_safety_read("/main.py") != restore_content:
        raise Exception("Restored main verification failed")
    print("BOOT_SAFETY:STATUS=OK")
    print("BOOT_SAFETY:ACTION=RESTORE_AUTORUN")
    print("BOOT_SAFETY:MAIN_EXISTS=1")
    print("BOOT_SAFETY:BACKUP_PATH=" + selected_backup)
    print("BOOT_SAFETY:CURRENT_BACKUP_PATH=" + current_backup_path)
    print("BOOT_SAFETY:BACKUPS=" + ",".join(boot_safety_backups()))
    print("BOOT_SAFETY:MESSAGE=Autorun restored")
except Exception as error:
    if not boot_safety_exists("/main.py") and current_existed:
        try:
            boot_safety_write("/main.py", current_content)
        except Exception as rollback_error:
            sys.print_exception(rollback_error)
    if boot_safety_exists(temporary_path):
        try:
            os.remove(temporary_path)
        except Exception:
            pass
    sys.print_exception(error)
    print("BOOT_SAFETY:STATUS=ERROR")
    print("BOOT_SAFETY:ACTION=RESTORE_AUTORUN")
    print("BOOT_SAFETY:BACKUPS=" + ",".join(boot_safety_backups()))
    print("BOOT_SAFETY:MESSAGE=" + boot_safety_message(error))
print("BOOT_SAFETY:SCRIPT_DONE")
`;
}
