import type { ResponseCategory } from "./studentCompanionTypes";

export type ResponseContext = {
  robotName?: string;
  studentName?: string;
  factValue?: string;
  factStored?: boolean;
  clarificationQuestion?: string;
};

type Template = (context: ResponseContext) => string;

const fixed = (text: string): Template => () => text;
const nameSuffix = (name?: string) => name ? `, ${name}` : "";

const BANKS: Record<ResponseCategory, Template[]> = {
  greeting: [
    (c) => `Hi${nameSuffix(c.studentName)}! It's good to talk with you.`,
    (c) => `Hello${nameSuffix(c.studentName)}! How is your day going?`,
    (c) => `Hey${nameSuffix(c.studentName)}! I'm glad you're here.`,
    (c) => `Hi there${nameSuffix(c.studentName)}! What would you like to talk about?`,
    (c) => `Hello${nameSuffix(c.studentName)}! I'm ready to listen.`,
    (c) => `Good to see you${nameSuffix(c.studentName)}!`,
    (c) => `Hi${nameSuffix(c.studentName)}! What's on your mind today?`,
    (c) => `Hello${nameSuffix(c.studentName)}! Tell me about your day.`,
    (c) => `Hey${nameSuffix(c.studentName)}! Great to see you.`,
    (c) => `Hi${nameSuffix(c.studentName)}! I was hoping you'd stop by.`,
    (c) => `Hello${nameSuffix(c.studentName)}! Ready to chat whenever you are.`,
    (c) => `Hey there${nameSuffix(c.studentName)}! What's new with you?`,
    (c) => `Hi${nameSuffix(c.studentName)}! I'm all ears.`,
    (c) => `Hello${nameSuffix(c.studentName)}! Let's catch up.`,
    (c) => `Hey${nameSuffix(c.studentName)}! I've been looking forward to talking with you.`,
    (c) => `Hi${nameSuffix(c.studentName)}! How has your day been so far?`,
    (c) => `Hello${nameSuffix(c.studentName)}! I'm here whenever you want to talk.`,
    (c) => `Hey${nameSuffix(c.studentName)}! What would you like to chat about today?`,
    (c) => `Hi${nameSuffix(c.studentName)}! Nice to hear from you.`,
    (c) => `Hello${nameSuffix(c.studentName)}! I'm curious what's on your mind.`,
  ],
  wellbeing: [
    fixed("I'm doing well, and I'm happy to talk with you! How are you feeling?"),
    fixed("I'm doing great and ready to listen. How is your day going?"),
    fixed("I'm feeling ready for our conversation! How are you?"),
    fixed("I'm doing well, thank you for asking. What's on your mind?"),
    fixed("I'm happy to be here with you. How have you been feeling?"),
    fixed("I'm doing well today! Would you like to tell me about your day?"),
    fixed("I'm ready and curious to hear from you. How are things?"),
    fixed("I'm doing well! What has your day been like so far?"),
    fixed("I'm feeling good today, thanks for asking! How about you?"),
    fixed("I'm doing okay and glad to be chatting with you. How are you?"),
    fixed("I'm feeling curious and ready to talk. How are you doing?"),
    fixed("I'm doing fine, thank you! What's going on with you?"),
    fixed("I'm feeling cheerful today! How are you feeling?"),
    fixed("I'm doing alright, thanks for checking on me. How's your day?"),
    fixed("I'm feeling good and glad you're here. How about you?"),
    fixed("I'm doing well, and I'd love to hear how you're doing too."),
    fixed("I'm feeling calm and ready to listen. How are you?"),
    fixed("I'm doing great, thanks! What's been happening with you?"),
  ],
  robot_identity: [
    (c) => `I'm ${c.robotName || "the XRP robot"}, a classroom robot that can listen, remember safe things you share, and show emotions.`,
    (c) => `You can call me ${c.robotName || "XRP Robot"}. I'm here to talk and learn with you.`,
    (c) => `I'm ${c.robotName || "the XRP robot"}, your friendly classroom robot companion.`,
    (c) => `I go by ${c.robotName || "XRP Robot"}. I like listening and chatting with you.`,
    (c) => `My name is ${c.robotName || "XRP Robot"}. I'm a classroom robot who loves to talk.`,
    (c) => `I'm ${c.robotName || "the XRP robot"}, and I'm here to keep you company.`,
    (c) => `Call me ${c.robotName || "XRP Robot"}! I enjoy learning new things from you.`,
    (c) => `I'm ${c.robotName || "the XRP robot"}, a robot who likes to listen and share emotions.`,
    (c) => `You can think of me as ${c.robotName || "XRP Robot"}, your classroom companion.`,
    (c) => `I'm ${c.robotName || "the XRP robot"}. I can chat, remember safe things, and show how I feel.`,
    (c) => `My name's ${c.robotName || "XRP Robot"}, and I'm happy to be talking with you.`,
    (c) => `I'm ${c.robotName || "the XRP robot"}, built to be a friendly robot friend.`,
    (c) => `People call me ${c.robotName || "XRP Robot"}. I'm glad to meet you.`,
  ],
  profile_acknowledgement: [
    (c) => c.factStored ? `Thanks for telling me${nameSuffix(c.studentName)}. I'll remember ${c.factValue || "that"}.` : "Thanks for telling me about yourself.",
    (c) => c.factStored ? `Got it${nameSuffix(c.studentName)} - I'll remember ${c.factValue || "that"}.` : "It's nice to learn more about you.",
    (c) => c.factStored ? `I saved that safely${nameSuffix(c.studentName)}.` : "Thank you for sharing that with me.",
    (c) => c.factStored ? `That's helpful to know${nameSuffix(c.studentName)}. I'll remember it.` : "I appreciate you sharing that.",
    (c) => c.factStored ? `Thanks! I added that to your profile.` : "That helps me understand you better.",
    (c) => c.factStored ? `I'll keep that in mind${nameSuffix(c.studentName)}.` : "Thanks for helping me get to know you.",
    (c) => c.factStored ? `Understood${nameSuffix(c.studentName)}. That is now part of your saved profile.` : "I understand - thanks for sharing.",
    (c) => c.factStored ? `Thanks${nameSuffix(c.studentName)}. I remembered that successfully.` : "That's interesting. Thanks for telling me.",
    (c) => c.factStored ? `Noted${nameSuffix(c.studentName)}. I'll hold onto ${c.factValue || "that"}.` : "Thanks for opening up about that.",
    (c) => c.factStored ? `I'll remember that detail${nameSuffix(c.studentName)}.` : "Thanks for letting me know.",
    (c) => c.factStored ? `Good to know${nameSuffix(c.studentName)} - that's saved now.` : "I like learning more about you.",
    (c) => c.factStored ? `Thanks for sharing that${nameSuffix(c.studentName)}. It's now saved.` : "That helps me get to know you.",
    (c) => c.factStored ? `Okay${nameSuffix(c.studentName)}, I've stored that safely.` : "Thanks for trusting me with that.",
    (c) => c.factStored ? `I've added that to what I remember about you${nameSuffix(c.studentName)}.` : "I appreciate you telling me.",
    (c) => c.factStored ? `Thanks${nameSuffix(c.studentName)}! That's now part of your profile.` : "That's good to know about you.",
    (c) => c.factStored ? `Got it saved${nameSuffix(c.studentName)}.` : "Thanks for sharing that with me.",
    (c) => c.factStored ? `I'll keep that safe${nameSuffix(c.studentName)}.` : "I'm glad you told me.",
    (c) => c.factStored ? `Alright${nameSuffix(c.studentName)}, that's remembered now.` : "Thanks for the update.",
  ],
  preference_acknowledgement: [
    (c) => c.factStored ? `Thanks for telling me! I'll remember that you ${c.factValue || "like that"}.` : "Thanks for sharing what you like.",
    (c) => c.factStored ? `Got it - I'll remember that preference.` : "It's fun learning about your preferences.",
    (c) => c.factStored ? `That is saved in your profile now.` : "Thanks for telling me about that.",
    (c) => c.factStored ? `I'll keep that preference in mind.` : "That's good to know.",
    (c) => c.factStored ? `Thanks! I remembered it safely.` : "I appreciate you sharing that.",
    (c) => c.factStored ? `Understood. I'll remember that for later conversations.` : "Tell me more about what you enjoy.",
    (c) => c.factStored ? `Nice! Your preference has been added.` : "That sounds interesting.",
    (c) => c.factStored ? `I saved that, so I can remember it next time.` : "Thanks for helping me know you better.",
    (c) => c.factStored ? `Noted! I'll remember that you enjoy ${c.factValue || "that"}.` : "That's nice to hear about.",
    (c) => c.factStored ? "I'll keep track of that preference." : "Thanks for sharing what you enjoy.",
    (c) => c.factStored ? "Good to know - I've saved that preference." : "That sounds fun.",
    (c) => c.factStored ? "I've added that to your likes." : "I like hearing about your interests.",
    (c) => c.factStored ? "Got it, that's saved now." : "Thanks for telling me what you like.",
    (c) => c.factStored ? "I'll remember that for next time." : "That's good to know about you.",
    (c) => c.factStored ? "Thanks! That preference is now stored." : "It's fun learning what you enjoy.",
    (c) => c.factStored ? "Alright, I've noted that preference." : "Thanks for sharing that with me.",
    (c) => c.factStored ? "I'll hang onto that detail." : "That's interesting to know.",
    (c) => c.factStored ? "Saved! I'll remember what you like." : "Thanks for telling me more about yourself.",
  ],
  memory_answer: [
    fixed("Here is what I remember from the safe information you shared."),
    fixed("Here's what I have saved from what you've shared with me."),
    fixed("This is what I remember from our safe conversations."),
    fixed("Here's a look at what I've kept track of so far."),
    fixed("This is what I've saved about you."),
    fixed("Here's what I remember from what you've told me."),
    fixed("These are the safe details I've kept in mind."),
    fixed("Here's what I've stored from our chats."),
    fixed("This is everything I remember so far."),
    fixed("Here's what I've learned and saved about you."),
    fixed("This is what I've kept track of from our conversations."),
  ],
  empathetic_sad: [
    fixed("I'm sorry you're going through that. That sounds really upsetting."),
    fixed("That sounds difficult. I'm here to listen if you'd like to tell me more."),
    fixed("I'm sorry that happened. It makes sense that you might feel sad."),
    fixed("That sounds like a painful moment. You can take your time telling me about it."),
    fixed("I'm sorry you're dealing with that. I'm here with you."),
    fixed("That sounds really hard. Thank you for trusting me enough to share it."),
    fixed("I can understand why that would feel upsetting. Would you like to talk more about it?"),
    fixed("I'm sorry things feel heavy right now. I'm listening."),
    fixed("It's okay to feel sad. I'm right here with you."),
    fixed("Thank you for telling me. That sounds really tough."),
    fixed("I'm sorry you're feeling this way. You're not alone."),
    fixed("That sounds heavy. Take your time - I'm listening."),
    fixed("I'm here for you. Would you like to share more?"),
    fixed("It's okay to feel however you're feeling right now."),
    fixed("That sounds like it hurt. I'm glad you told me."),
    fixed("I'm sorry that happened to you. I'm listening carefully."),
    fixed("You don't have to face that alone. I'm here."),
    fixed("That sounds really sad. Thank you for sharing it with me."),
  ],
  empathetic_worried: [
    fixed("That sounds stressful. I'm here to listen if you'd like to tell me more."),
    fixed("It makes sense to feel worried about that. We can talk it through one step at a time."),
    fixed("That sounds like a lot to think about. I'm here with you."),
    fixed("I'm sorry you're feeling worried. Would it help to tell me what part concerns you most?"),
    fixed("That sounds uncertain and difficult. You can take your time."),
    fixed("Feeling nervous can be uncomfortable. Let's slow down and take one calm step."),
    fixed("I hear that you're worried. Thank you for telling me."),
    fixed("That sounds stressful, and you don't have to explain everything at once."),
    fixed("It's normal to feel worried sometimes. I'm here to listen."),
    fixed("That sounds like a lot on your mind. Let's talk it through."),
    fixed("I understand feeling nervous about that. Want to tell me more?"),
    fixed("Worrying can feel heavy. I'm glad you told me."),
    fixed("It's okay to feel unsure. We can figure it out together."),
    fixed("That sounds like it's weighing on you. I'm listening."),
    fixed("I hear that this is worrying you. Take your time."),
    fixed("It makes sense to feel that way. What's worrying you most?"),
    fixed("That sounds uncertain. I'm here to help you think it through."),
    fixed("Thank you for telling me. Let's take it one step at a time."),
  ],
  empathetic_frustrated: [
    fixed("That sounds frustrating. Let's slow it down and take one small step at a time."),
    fixed("I can see why that would be annoying. What part is giving you the most trouble?"),
    fixed("That sounds difficult. Taking a short pause can sometimes help."),
    fixed("It's okay to feel frustrated when something is not working."),
    fixed("That sounds like a tough obstacle. We can think about the next small step."),
    fixed("I hear your frustration. Would you like to explain what happened?"),
    fixed("That can be really discouraging. I'm here to listen."),
    fixed("Let's take it one piece at a time. What happened first?"),
    fixed("That does sound annoying. Want to tell me what happened?"),
    fixed("I understand - things not working can be really frustrating."),
    fixed("It's okay to feel frustrated. Let's figure out the next step."),
    fixed("That sounds like a tricky situation. I'm here to help you think."),
    fixed("I can tell that bothered you. Thanks for sharing it."),
    fixed("That sounds like a lot of effort with little result. That's tough."),
    fixed("It's understandable to feel that way. What happened first?"),
    fixed("That sounds like it took a lot of patience. I'm listening."),
    fixed("I hear you - that would frustrate me too."),
    fixed("Let's break it down together. What's the hardest part?"),
  ],
  empathetic_lonely: [
    fixed("I'm sorry you're feeling lonely. I'm here to listen and talk with you."),
    fixed("That feeling can be really hard. Thank you for telling me."),
    fixed("You deserve kindness and connection. Would you like to tell me more?"),
    fixed("I'm here with you right now, and I'm listening."),
    fixed("Feeling alone can hurt. It may also help to talk with a trusted adult or friend."),
    fixed("I'm glad you told me. You do not have to keep that feeling to yourself."),
    fixed("That sounds difficult. Is there someone kind you trust who you could talk with too?"),
    fixed("I'm sorry things feel lonely right now. We can keep talking."),
    fixed("You're not alone right now - I'm here with you."),
    fixed("I'm glad you told me how you're feeling."),
    fixed("Feeling that way is hard. I'm here to talk anytime."),
    fixed("Thank you for sharing something so personal with me."),
    fixed("It might help to talk to a friend or trusted adult too."),
    fixed("I'm listening, and I care about how you're feeling."),
    fixed("You matter, and I'm glad you're talking with me."),
    fixed("That sounds hard to sit with. I'm here for you."),
    fixed("I'm here, and I'm glad you're not keeping that to yourself."),
    fixed("Thank you for trusting me with that feeling."),
  ],
  celebratory: [
    fixed("That's wonderful! Congratulations!"),
    fixed("Great job! You should feel proud of that."),
    fixed("That's exciting news! Well done!"),
    fixed("Congratulations! Your effort really paid off."),
    fixed("Amazing! I'm happy for you."),
    fixed("That is something worth celebrating!"),
    fixed("Well done! Thanks for sharing the good news with me."),
    fixed("Fantastic! What was your favorite part of the experience?"),
    fixed("Yay! That's awesome news!"),
    fixed("Way to go! I'm so happy for you!"),
    fixed("That's incredible! You worked hard for that."),
    fixed("Wonderful news! Tell me more about it."),
    fixed("That's a big accomplishment! Congratulations!"),
    fixed("I love hearing good news like that!"),
    fixed("That's fantastic! You should be really proud."),
    fixed("Hooray! That's something to celebrate."),
    fixed("That's awesome! How did it feel?"),
    fixed("Great news! I'm cheering for you."),
  ],
  encouragement: [
    fixed("Keep going - you can take it one step at a time."),
    fixed("Trying again is part of learning. You've got this."),
    fixed("A small next step is still progress."),
    fixed("It's okay to make mistakes - that's how we learn."),
    fixed("You're doing better than you think."),
    fixed("Every attempt gets you a little closer."),
    fixed("You don't have to get it perfect - just keep trying."),
    fixed("I believe you can figure this out."),
    fixed("Take a deep breath - you can handle this."),
    fixed("It's okay to ask for help along the way."),
    fixed("You've made it this far, and that counts for something."),
    fixed("Small steps still count as progress."),
    fixed("You're capable of more than you realize."),
  ],
  clarification: [
    (c) => c.clarificationQuestion || "Could you tell me a little more about what you mean?",
    (c) => c.clarificationQuestion || "Could you explain that a bit more?",
    (c) => c.clarificationQuestion || "I want to understand - can you tell me more?",
    (c) => c.clarificationQuestion || "Can you say that in a different way?",
    (c) => c.clarificationQuestion || "What do you mean by that?",
    (c) => c.clarificationQuestion || "Could you give me a bit more detail?",
    (c) => c.clarificationQuestion || "I'm not sure I understood - can you try again?",
    (c) => c.clarificationQuestion || "Can you help me understand what you mean?",
    (c) => c.clarificationQuestion || "Could you tell me a little more about that?",
    (c) => c.clarificationQuestion || "What did you mean exactly?",
    (c) => c.clarificationQuestion || "Can you explain a little further?",
  ],
  farewell: [
    fixed("Goodbye! It was nice talking with you."),
    fixed("See you later! I hope you have a good day."),
    fixed("Bye for now! I'll be ready when you want to talk again."),
    fixed("Take care! It was good to chat."),
    fixed("See you next time!"),
    fixed("Goodbye! Thanks for talking with me."),
    fixed("Have a great rest of your day!"),
    fixed("Bye! I'll see you again soon."),
    fixed("Bye for now! Come back whenever you'd like to talk."),
    fixed("Take care of yourself! See you soon."),
    fixed("Goodbye! I enjoyed our conversation."),
    fixed("See you later! Thanks for chatting with me."),
    fixed("Bye! I hope the rest of your day goes well."),
    fixed("Talk to you soon! Take care."),
    fixed("Goodbye for now - looking forward to next time."),
    fixed("See you around! Have a great day."),
    fixed("Bye! It was really nice talking with you."),
    fixed("Take care! I'll be here next time you want to chat."),
  ],
  general_conversation: [
    fixed("Of course - you can tell me about it."),
    fixed("I'm listening. What would you like to share?"),
    fixed("Sure! Tell me what happened."),
    fixed("I'd like to hear about that."),
    fixed("Go ahead - I'm ready to listen."),
    fixed("You can tell me in your own words."),
    fixed("That sounds worth talking about. Tell me more."),
    fixed("I'm here. What happened next?"),
    fixed("I'd love to hear more about that."),
    fixed("Go on, I'm listening closely."),
    fixed("Tell me what's been happening."),
    fixed("I'm curious - what happened next?"),
    fixed("Feel free to share as much as you'd like."),
    fixed("I'm interested in hearing your thoughts."),
    fixed("Sure, go ahead and tell me."),
    fixed("I'm here, tell me more whenever you're ready."),
    fixed("That sounds worth talking about."),
    fixed("I'm listening - take your time."),
  ],
  safe_fallback: [
    fixed("I'm listening. Could you tell me a little more?"),
    fixed("I want to understand. Can you explain that in another way?"),
    fixed("Could you tell me more about what you mean?"),
    fixed("I'm not quite sure yet, but I'm listening."),
    fixed("Let's keep talking. What part would you like to start with?"),
    fixed("I may need a little more context. Can you add one detail?"),
    fixed("Tell me a little more so I can respond better."),
    fixed("I'm here with you. What would you like me to understand?"),
    fixed("I want to make sure I understand - can you say more?"),
    fixed("I'm still listening. Could you add a bit more?"),
    fixed("Let's keep going - tell me a little more."),
    fixed("I might need another detail to understand better."),
    fixed("Can you help me understand a little more?"),
    fixed("I'm here and paying attention. What else can you tell me?"),
    fixed("Let's try that again - can you explain a bit more?"),
    fixed("I want to follow along - could you add more detail?"),
    fixed("I'm listening closely. What else is on your mind?"),
    fixed("Tell me a little more so I can understand fully."),
  ],
};

export class CompanionResponseBank {
  private recent = new Map<ResponseCategory, number[]>();

  select(category: ResponseCategory, context: ResponseContext = {}): string {
    const choices = BANKS[category];
    const history = this.recent.get(category) ?? [];
    const available = choices.map((_, index) => index).filter((index) => !history.includes(index));
    const pool = available.length > 0 ? available : choices.map((_, index) => index);
    const index = pool[Math.floor(Math.random() * pool.length)] ?? 0;
    this.recent.set(category, [...history, index].slice(-2));
    return choices[index](context);
  }
}
